apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: hlt

data:
  DB_URL: "r2dbc:postgresql://auth-postgres.hlt.svc.cluster.local:5432/auth_db"
  DB_URL_JDBC: "jdbc:postgresql://auth-postgres.hlt.svc.cluster.local:5432/auth_db"