apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service
  namespace: hlt

spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker-container
          image: ghcr.io/salmanov-nariman/hlt-worker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 50051