apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: hlt

spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat-container
          image: ghcr.io/salmanov-nariman/hlt-chat:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080