// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: api/worker.proto

package worker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDuoMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DuoId         string                 `protobuf:"bytes,1,opt,name=duo_id,json=duoId,proto3" json:"duo_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDuoMembersRequest) Reset() {
	*x = GetDuoMembersRequest{}
	mi := &file_api_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDuoMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDuoMembersRequest) ProtoMessage() {}

func (x *GetDuoMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDuoMembersRequest.ProtoReflect.Descriptor instead.
func (*GetDuoMembersRequest) Descriptor() ([]byte, []int) {
	return file_api_worker_proto_rawDescGZIP(), []int{0}
}

func (x *GetDuoMembersRequest) GetDuoId() string {
	if x != nil {
		return x.DuoId
	}
	return ""
}

func (x *GetDuoMembersRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

type GetDuoMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDuoMembersResponse) Reset() {
	*x = GetDuoMembersResponse{}
	mi := &file_api_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDuoMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDuoMembersResponse) ProtoMessage() {}

func (x *GetDuoMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDuoMembersResponse.ProtoReflect.Descriptor instead.
func (*GetDuoMembersResponse) Descriptor() ([]byte, []int) {
	return file_api_worker_proto_rawDescGZIP(), []int{1}
}

func (x *GetDuoMembersResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

var File_api_worker_proto protoreflect.FileDescriptor

const file_api_worker_proto_rawDesc = "" +
	"\n" +
	"\x10api/worker.proto\x12\x06worker\"J\n" +
	"\x14GetDuoMembersRequest\x12\x15\n" +
	"\x06duo_id\x18\x01 \x01(\tR\x05duoId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\"2\n" +
	"\x15GetDuoMembersResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds2]\n" +
	"\rWorkerService\x12L\n" +
	"\rGetDuoMembers\x12\x1c.worker.GetDuoMembersRequest\x1a\x1d.worker.GetDuoMembersResponseB\x0fZ\rpkg/pb/workerb\x06proto3"

var (
	file_api_worker_proto_rawDescOnce sync.Once
	file_api_worker_proto_rawDescData []byte
)

func file_api_worker_proto_rawDescGZIP() []byte {
	file_api_worker_proto_rawDescOnce.Do(func() {
		file_api_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_worker_proto_rawDesc), len(file_api_worker_proto_rawDesc)))
	})
	return file_api_worker_proto_rawDescData
}

var file_api_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_worker_proto_goTypes = []any{
	(*GetDuoMembersRequest)(nil),  // 0: worker.GetDuoMembersRequest
	(*GetDuoMembersResponse)(nil), // 1: worker.GetDuoMembersResponse
}
var file_api_worker_proto_depIdxs = []int32{
	0, // 0: worker.WorkerService.GetDuoMembers:input_type -> worker.GetDuoMembersRequest
	1, // 1: worker.WorkerService.GetDuoMembers:output_type -> worker.GetDuoMembersResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_worker_proto_init() }
func file_api_worker_proto_init() {
	if File_api_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_worker_proto_rawDesc), len(file_api_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_worker_proto_goTypes,
		DependencyIndexes: file_api_worker_proto_depIdxs,
		MessageInfos:      file_api_worker_proto_msgTypes,
	}.Build()
	File_api_worker_proto = out.File
	file_api_worker_proto_goTypes = nil
	file_api_worker_proto_depIdxs = nil
}
